on:
  schedule:
    # 日本時間で月〜金の毎日9時30分に実行
    - cron: 30 0 ? SUN-THU *

name: Start Instance

jobs:
  start:
    name: Start Instance
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Install awscli
        run: pip install --upgrade pip awscli

      - name: Start Instance
        run: ./scripts/instance.bash start
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          RESOURCE_NAME: ${{ secrets.RESOURCE_NAME }}
