on:
  schedule:
    # 日本時間で毎日19時30分に実行
    - cron: 30 10 * ? *

name: Stop Instance

jobs:
  stop:
    name: Stop Instance
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Install awscli
        run: pip install --upgrade pip awscli

      - name: Stop Instance
        run: ./scripts/instance.bash stop
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          RESOURCE_NAME: ${{ secrets.RESOURCE_NAME }}
